name: Build and Push Microservices to ECR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services_changed: ${{ steps.filter.outputs.services_changed }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            adservice:
              - 'src/adservice/**'
            cartservice:
              - 'src/cartservice/src/**'
            checkoutservice:
              - 'src/checkoutservice/**'
            currencyservice:
              - 'src/currencyservice/**'
            emailservice:
              - 'src/emailservice/**'
            frontend:
              - 'src/frontend/**'
            loadgenerator:
              - 'src/loadgenerator/**'
            paymentservice:
              - 'src/paymentservice/**'
            productcatalogservice:
              - 'src/productcatalogservice/**'
            recommendationservice:
              - 'src/recommendationservice/**'
            shippingservice:
              - 'src/shippingservice/**'
            shoppingassistantservice:
              - 'src/shoppingassistantservice/**'

      - name: Set changed services output
        run: |
          SERVICES=()
          for svc in adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice shoppingassistantservice; do
            if [[ "${{ steps.filter.outputs[$svc] }}" == 'true' ]]; then
              SERVICES+=("\"$svc\"")
            fi
          done
          echo "::set-output name=services_changed::[$(IFS=,; echo "${SERVICES[*]}")]"
        shell: bash

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
        matrix:
            service: ${{ fromJson(needs.detect-changes.outputs.services_changed) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image
        run: |
          SERVICE=${{ matrix.service }}
          ENVIRONMENT=${{ github.event.inputs.environment }}
          IMAGE_TAG=$(echo "${{ github.sha }}" | cut -c1-7)
          ECR_REPO="${{ env.ECR_REGISTRY }}/${SERVICE}"

          DOCKER_CONTEXT="./src/$SERVICE"
          DOCKERFILE_PATH="$DOCKER_CONTEXT/Dockerfile"

          if [ "$SERVICE" = "cartservice" ]; then
            DOCKER_CONTEXT="./src/$SERVICE/src"
            DOCKERFILE_PATH="./src/$SERVICE/src/Dockerfile"
          fi

          docker build -t $ECR_REPO:$IMAGE_TAG -f $DOCKERFILE_PATH $DOCKER_CONTEXT
          echo "Pushing image with tag $IMAGE_TAG (SHA)..."
          docker push $ECR_REPO:$IMAGE_TAG

          docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:$ENVIRONMENT
          echo "Pushing image with tag $ENVIRONMENT..."
          docker push $ECR_REPO:$ENVIRONMENT