name: Build and Push Microservices to ECR

on:
    workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [adservice,cartservice,checkoutservice] # Add your microservice directories here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image
        run: |
          SERVICE=${{ matrix.service }}
          IMAGE_TAG=dev
          ECR_REPO="${{ env.ECR_REGISTRY }}/${SERVICE}"

          DOCKER_CONTEXT="./src/$SERVICE"
          DOCKERFILE_PATH="$DOCKER_CONTEXT/Dockerfile"

          if [ "$SERVICE" = "cartservice" ]; then
            DOCKER_CONTEXT="./src/$SERVICE/src"
            DOCKERFILE_PATH="./src/$SERVICE/src/Dockerfile"
          fi

          echo "Building $SERVICE..."
          docker build -t $ECR_REPO:$IMAGE_TAG -f $DOCKERFILE_PATH $DOCKER_CONTEXT

          echo "Pushing to ECR..."
          docker push $ECR_REPO:$IMAGE_TAG